# Generated by Django 3.2.3 on 2021-06-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pakages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='picture')),
                ('time_day', models.IntegerField()),
                ('time_night', models.IntegerField()),
                ('star', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
